Theme Update
UWCS/uwcs-dextre pull request #53
Opened 2022-09-10 21:28 UTC by Levelent

A few small changes to drop the shield, switch out the logo/background, and make small improvements such as renaming one of the exec roles and editing a hard-coded url.

2022-09-11 15:02 UTC, joshdavies14 requested changes
Few comments on things, along with the following:
- `logo.svg` is used in places the CMS, so references to this file in `‎lib/templates/wagtailadmin/404.html` and `lib/templates/wagtailadmin/base.html` need to be updated to the new logo location.
- In the `sponsor_homepage` and `sponsor_sidebar` templates, worth noting that there might end up being merge conflicts down the line with changes I made in the dark-mode-fixes branch, but those changes are fine.
- PR should be merging into the `develop` branch, not `master`

2022-09-15 17:47 UTC, Levelent commented on static/scss/new/_settings_base.scss
> +$primary: #3A7DFF;
Updated the blue to 3A69FF to pass contrast checks against white - the previous yellow was already failing contrast checks, this one fails them less.

2022-09-16 14:28 UTC, joshdavies14 commented on static/scss/new/_settings_base.scss
> +$primary: #3A7DFF;
`#3A69FF` still fails contrast checks against the two greys in use on the site: see https://webaim.org/resources/contrastchecker/?fcolor=3A69FF&bcolor=2C3134 and https://webaim.org/resources/contrastchecker/?fcolor=3A69FF&bcolor=2D3338

2022-09-16 15:12 UTC, Levelent commented on static/scss/new/_settings_base.scss
> +$primary: #3A7DFF;
So did the previous blue, if you check - we never use that colour combination for text, so this shouldn't be an issue. It even passes contrast checks on the greys more than 3D5AFE does, the original colour.

2022-09-16 20:32 UTC, joshdavies14 commented on static/scss/new/_settings_base.scss
> +$primary: #3A7DFF;
I agree on the blue being better than before with the greys; however, commit 9e491f66eaae3c1f318c568f939dd158fc74b1d9 was written to not use the original blue against grey backgrounds (primarily in dark mode) to mitigate the accessibility issues. If you want to revert to the original/actual blue in dark mode (as indicated in #48), then the contrast checks should be passing against the greys too.

2022-09-22 18:41 UTC, Levelent commented
Discussed on Discord, fine to merge now and and fix link colours later as a separate issue

2022-09-22 18:42 UTC, merged